{% set name = "eqt" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eqt-{{ version }}.tar.gz
  sha256: 11a94cac20ef84473551cb40cb42bf3420c2257087f32d5eb73de2369fa9a40d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }},<3.12
    - pyside2
    - qdarkstyle

test:
  imports:
    - eqt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/TomographicImaging/eqt
  summary: A number of templates and tools to develop Qt GUIs with Python effectively
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - casperdcl
    - paskino
